"""Initial schema migration

Revision ID: 268fab47004c
Revises: 
Create Date: 2026-05-03 10:50:14.234101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '268fab47004c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester_start', sa.DateTime(), nullable=False),
    sa.Column('semester_end', sa.DateTime(), nullable=False),
    sa.Column('total_helb_amount', sa.Float(), nullable=False),
    sa.Column('rent_allocation', sa.Float(), nullable=False),
    sa.Column('food_allocation', sa.Float(), nullable=False),
    sa.Column('transport_allocation', sa.Float(), nullable=False),
    sa.Column('personal_needs_allocation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_allocations_id'), 'budget_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_budget_allocations_user_id'), 'budget_allocations', ['user_id'], unique=False)
    op.create_table('counselling_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counselling_sessions_id'), 'counselling_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_counselling_sessions_user_id'), 'counselling_sessions', ['user_id'], unique=False)
    op.create_table('emergency_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reserved_percentage', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('remaining_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_funds_id'), 'emergency_funds', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_funds_user_id'), 'emergency_funds', ['user_id'], unique=True)
    op.create_table('expenditure_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount_spent', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenditure_snapshots_category'), 'expenditure_snapshots', ['category'], unique=False)
    op.create_index(op.f('ix_expenditure_snapshots_id'), 'expenditure_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_expenditure_snapshots_month'), 'expenditure_snapshots', ['month'], unique=False)
    op.create_index(op.f('ix_expenditure_snapshots_user_id'), 'expenditure_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_expenditure_snapshots_year'), 'expenditure_snapshots', ['year'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_user_id', sa.Integer(), nullable=False),
    sa.Column('borrower_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_borrower_user_id'), 'loans', ['borrower_user_id'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_lender_user_id'), 'loans', ['lender_user_id'], unique=False)
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_transactions_id'), 'mpesa_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_transaction_id'), 'mpesa_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_mpesa_transactions_user_id'), 'mpesa_transactions', ['user_id'], unique=False)
    op.create_table('offline_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_queue_id'), 'offline_queue', ['id'], unique=False)
    op.create_index(op.f('ix_offline_queue_user_id'), 'offline_queue', ['user_id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('eligibility_criteria', sa.Text(), nullable=False),
    sa.Column('application_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_table('shared_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('split_among_user_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_expenses_group_id'), 'shared_expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_shared_expenses_id'), 'shared_expenses', ['id'], unique=False)
    op.create_table('student_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inflation_report', sa.String(), nullable=False),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_feedbacks_id'), 'student_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_student_feedbacks_user_id'), 'student_feedbacks', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('withdrawal_limit_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_limit_amount', sa.Float(), nullable=False),
    sa.Column('current_daily_withdrawn', sa.Float(), nullable=False),
    sa.Column('last_reset_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_limit_settings_id'), 'withdrawal_limit_settings', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawal_limit_settings_user_id'), 'withdrawal_limit_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_limit_settings_user_id'), table_name='withdrawal_limit_settings')
    op.drop_index(op.f('ix_withdrawal_limit_settings_id'), table_name='withdrawal_limit_settings')
    op.drop_table('withdrawal_limit_settings')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_student_feedbacks_user_id'), table_name='student_feedbacks')
    op.drop_index(op.f('ix_student_feedbacks_id'), table_name='student_feedbacks')
    op.drop_table('student_feedbacks')
    op.drop_index(op.f('ix_shared_expenses_id'), table_name='shared_expenses')
    op.drop_index(op.f('ix_shared_expenses_group_id'), table_name='shared_expenses')
    op.drop_table('shared_expenses')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_offline_queue_user_id'), table_name='offline_queue')
    op.drop_index(op.f('ix_offline_queue_id'), table_name='offline_queue')
    op.drop_table('offline_queue')
    op.drop_index(op.f('ix_mpesa_transactions_user_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_transaction_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_id'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    op.drop_index(op.f('ix_loans_lender_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_user_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_expenditure_snapshots_year'), table_name='expenditure_snapshots')
    op.drop_index(op.f('ix_expenditure_snapshots_user_id'), table_name='expenditure_snapshots')
    op.drop_index(op.f('ix_expenditure_snapshots_month'), table_name='expenditure_snapshots')
    op.drop_index(op.f('ix_expenditure_snapshots_id'), table_name='expenditure_snapshots')
    op.drop_index(op.f('ix_expenditure_snapshots_category'), table_name='expenditure_snapshots')
    op.drop_table('expenditure_snapshots')
    op.drop_index(op.f('ix_emergency_funds_user_id'), table_name='emergency_funds')
    op.drop_index(op.f('ix_emergency_funds_id'), table_name='emergency_funds')
    op.drop_table('emergency_funds')
    op.drop_index(op.f('ix_counselling_sessions_user_id'), table_name='counselling_sessions')
    op.drop_index(op.f('ix_counselling_sessions_id'), table_name='counselling_sessions')
    op.drop_table('counselling_sessions')
    op.drop_index(op.f('ix_budget_allocations_user_id'), table_name='budget_allocations')
    op.drop_index(op.f('ix_budget_allocations_id'), table_name='budget_allocations')
    op.drop_table('budget_allocations')
    # ### end Alembic commands ###
